version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/ecommerce-api
    ports:
      - 8080:8080
    image: app:ecommerce
    container_name: ecommerce_container
    command: python manage.py runserver 0.0.0.0:8080
    environment: 
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on: 
      - ecomm_db
      - redis
  
  ecomm_db:
    image: postgres
    environment:
      POSTGRES_USER: emmanuel
      POSTGRES_DB: constructionstore
      POSTGRES_PASSWORD: inioluwa1
    volumes:
      - pgdata:/var/lib/posgresql/data
    ports:
       - 5431:5431

  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/usr/src/app
    depends_on: 
      - app
      - redis
  
  redis:
    image: "redis:6.0.15"

volumes:
  pgdata: