version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/ecommerce-api
    ports:
      - 8000:8000
    image: app:ecommerce
    container_name: ecommerce_container
    command: python manage.py runserver 0.0.0.0:8000
    environment: 
      - CELERY_BROKER=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
    depends_on: 
      - ecomm_db
      - redis
  
  ecomm_db:
    image: postgres
    environment:
      POSTGRES_USER: ${ECOMMUSER}
      POSTGRES_DB: ${ECOMMNAME}
      POSTGRES_PASSWORD: ${ECOMMPASSWORD}
    volumes:
      - pgdata:/var/lib/posgresql/data
    ports:
       - 5431:5431

  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/usr/src/app
    depends_on: 
      - app
      - redis
  
  redis:
    image: "redis:6.0.15"

volumes:
  pgdata:
 
