# Generated by Django 3.2.4 on 2021-09-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price_ngn', models.PositiveIntegerField()),
                ('product_description', models.TextField(blank=True, max_length=500)),
                ('available_inventory', models.PositiveIntegerField(default=1)),
                ('product_image', models.ImageField(default='/home/emmanuel/Emmanuel/IT-Internship/user-avatar.png', upload_to='profile_pics')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
        ),
    ]
