# Generated by Django 3.2.4 on 2021-09-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-category_name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
