# Generated by Django 3.2.4 on 2021-09-09 10:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_remove_cart_total'),
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedOutOrder',
            fields=[
                ('purchase_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('success', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.cart')),
                ('coupon_applied', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Checkout.coupon')),
            ],
        ),
    ]
