# Generated by Django 3.2.4 on 2021-09-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkedoutorder',
            options={'ordering': ['-date_placed']},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='checkedoutorder',
            name='date_placed',
            field=models.DateField(auto_now=True),
        ),
    ]
