# Generated by Django 3.2.4 on 2021-09-09 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_remove_cart_total'),
        ('Checkout', '0002_checkedoutorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='one_time_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkedoutorder',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Cart.cart'),
        ),
    ]
