# Generated by Django 3.2.4 on 2021-09-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0004_trackcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedoutorder',
            name='coupon_applied',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Checkout.coupon'),
        ),
    ]
