# Generated by Django 3.2.4 on 2021-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_auto_20210910_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
