# Generated by Django 3.2.4 on 2021-09-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
