# Generated by Django 3.2.4 on 2021-09-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_auto_20210910_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-added_at']},
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='created_at',
            new_name='added_at',
        ),
    ]
